# Generated by Django 4.0.3 on 2022-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.CharField(default='', max_length=50)),
                ('info', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
