# Generated by Django 4.0.3 on 2022-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
